branch-defaults:
  master:
    environment: nodeserver-env
environment-defaults:
  nodeserver-env:
    branch: null
    repository: null
global:
  application_name: nodeserver
  default_ec2_keyname: Development
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.4.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: nickprivate
  sc: git
  workspace_type: Application
